Repository AdobeDocs/commerce-admin-developer, pull requests merged in 2023-03, with the labels that each got.

#47 Prepare for required workflow
  .github/linters/.markdownlint.yml
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
  .markdownlint.yml
  CODE_OF_CONDUCT.md
  README.md
  package.json
  yarn.lock
Labels: maintenance

#48 Change indexing cron to monthly
  .github/workflows/index.yml
Labels: maintenance

#46 Fixed typo and condensed summary description
  src/pages/pattern-library/containers/slideouts-modals-overlays.md
Labels: editorial, internal

#51 COMDOX-588: Update issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/incorrect_topic.yaml
  .github/ISSUE_TEMPLATE/missing_content.yaml
  .github/ISSUE_TEMPLATE/site_bug.yaml
  .github/ISSUE_TEMPLATE/site_feature.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
Labels: maintenance

#53 COMDOX-596: Update gatsby-theme-aio to 4.9.0
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: maintenance, dependencies
